# Generated by Django 6.0.3 on 2026-03-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cash', models.FloatField(default=0)),
                ('gpay', models.FloatField(default=0)),
                ('expense', models.FloatField(default=0)),
            ],
        ),
    ]
