# Generated by Django 6.0.2 on 2026-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('xe', models.IntegerField(default=0)),
                ('press', models.IntegerField(default=0)),
                ('online', models.IntegerField(default=0)),
                ('color', models.IntegerField(default=0)),
                ('xg', models.IntegerField(default=0)),
                ('pg', models.IntegerField(default=0)),
                ('og', models.IntegerField(default=0)),
                ('cg', models.IntegerField(default=0)),
            ],
        ),
    ]
