# Generated by Django 6.0.3 on 2026-03-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('xe', models.FloatField(default=0)),
                ('press', models.FloatField(default=0)),
                ('online', models.FloatField(default=0)),
                ('color', models.FloatField(default=0)),
                ('recharge', models.FloatField(default=0)),
                ('xg', models.FloatField(default=0)),
                ('pg', models.FloatField(default=0)),
                ('og', models.FloatField(default=0)),
                ('cg', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
