# Generated by Django 6.0.3 on 2026-04-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='recharge',
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='cg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='color',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='og',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='online',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='pg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='press',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='xe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='xg',
            field=models.IntegerField(default=0),
        ),
    ]
